#! /bin/sh
#

mkdir -p ../../../devel30/share/codeblocks/images/fortranproject> /dev/null 2> /dev/null
mkdir -p ../../../output30/share/codeblocks/images/fortranproject > /dev/null 2> /dev/null
cp ./images/fortranproject/*.* ../../../devel30/share/codeblocks/images/fortranproject/ > /dev/null 2> /dev/null
cp ./images/fortranproject/*.* ../../../output30/share/codeblocks/images/fortranproject/ > /dev/null 2> /dev/null
exit 0


