#! /bin/sh
CB_DEVEL=devel$1
CB_OUTPUT=output$1
CB_DEVEL_RESDIR=$CB_DEVEL/share/codeblocks
CB_OUTPUT_RESDIR=$CB_OUTPUT/share/codeblocks

mkdir -p ../../../$CB_DEVEL_RESDIR/images/fortranproject        > /dev/null 2> /dev/null
mkdir -p ../../../$CB_DEVEL_RESDIR/images/fortranproject/16x16  > /dev/null 2> /dev/null
mkdir -p ../../../$CB_DEVEL_RESDIR/images/fortranproject/20x20  > /dev/null 2> /dev/null
mkdir -p ../../../$CB_DEVEL_RESDIR/images/fortranproject/24x24  > /dev/null 2> /dev/null
mkdir -p ../../../$CB_DEVEL_RESDIR/images/fortranproject/28x28  > /dev/null 2> /dev/null
mkdir -p ../../../$CB_DEVEL_RESDIR/images/fortranproject/32x32  > /dev/null 2> /dev/null
mkdir -p ../../../$CB_DEVEL_RESDIR/images/fortranproject/40x40  > /dev/null 2> /dev/null
mkdir -p ../../../$CB_DEVEL_RESDIR/images/fortranproject/48x48  > /dev/null 2> /dev/null
mkdir -p ../../../$CB_DEVEL_RESDIR/images/fortranproject/56x56  > /dev/null 2> /dev/null
mkdir -p ../../../$CB_DEVEL_RESDIR/images/fortranproject/64x64  > /dev/null 2> /dev/null
mkdir -p ../../../$CB_DEVEL_RESDIR/images/fortranproject/svg    > /dev/null 2> /dev/null
mkdir -p ../../../$CB_OUTPUT_RESDIR/images/fortranproject       > /dev/null 2> /dev/null
mkdir -p ../../../$CB_OUTPUT_RESDIR/images/fortranproject/16x16 > /dev/null 2> /dev/null
mkdir -p ../../../$CB_OUTPUT_RESDIR/images/fortranproject/20x20 > /dev/null 2> /dev/null
mkdir -p ../../../$CB_OUTPUT_RESDIR/images/fortranproject/24x24 > /dev/null 2> /dev/null
mkdir -p ../../../$CB_OUTPUT_RESDIR/images/fortranproject/28x28 > /dev/null 2> /dev/null
mkdir -p ../../../$CB_OUTPUT_RESDIR/images/fortranproject/32x32 > /dev/null 2> /dev/null
mkdir -p ../../../$CB_OUTPUT_RESDIR/images/fortranproject/40x40 > /dev/null 2> /dev/null
mkdir -p ../../../$CB_OUTPUT_RESDIR/images/fortranproject/48x48 > /dev/null 2> /dev/null
mkdir -p ../../../$CB_OUTPUT_RESDIR/images/fortranproject/56x56 > /dev/null 2> /dev/null
mkdir -p ../../../$CB_OUTPUT_RESDIR/images/fortranproject/64x64 > /dev/null 2> /dev/null
mkdir -p ../../../$CB_OUTPUT_RESDIR/images/fortranproject/svg   > /dev/null 2> /dev/null
cp ./images/fortranproject/*.*       ../../../$CB_DEVEL_RESDIR/images/fortranproject/        > /dev/null 2> /dev/null
cp ./images/fortranproject/16x16/*.* ../../../$CB_DEVEL_RESDIR/images/fortranproject/16x16/  > /dev/null 2> /dev/null
cp ./images/fortranproject/20x20/*.* ../../../$CB_DEVEL_RESDIR/images/fortranproject/20x20/  > /dev/null 2> /dev/null
cp ./images/fortranproject/24x24/*.* ../../../$CB_DEVEL_RESDIR/images/fortranproject/24x24/  > /dev/null 2> /dev/null
cp ./images/fortranproject/28x28/*.* ../../../$CB_DEVEL_RESDIR/images/fortranproject/28x28/  > /dev/null 2> /dev/null
cp ./images/fortranproject/32x32/*.* ../../../$CB_DEVEL_RESDIR/images/fortranproject/32x32/  > /dev/null 2> /dev/null
cp ./images/fortranproject/40x40/*.* ../../../$CB_DEVEL_RESDIR/images/fortranproject/40x40/  > /dev/null 2> /dev/null
cp ./images/fortranproject/48x48/*.* ../../../$CB_DEVEL_RESDIR/images/fortranproject/48x48/  > /dev/null 2> /dev/null
cp ./images/fortranproject/56x56/*.* ../../../$CB_DEVEL_RESDIR/images/fortranproject/56x56/  > /dev/null 2> /dev/null
cp ./images/fortranproject/64x64/*.* ../../../$CB_DEVEL_RESDIR/images/fortranproject/64x64/  > /dev/null 2> /dev/null
cp ./images/fortranproject/svg/*.*   ../../../$CB_DEVEL_RESDIR/images/fortranproject/svg/    > /dev/null 2> /dev/null
cp ./images/fortranproject/*.*       ../../../$CB_OUTPUT_RESDIR/images/fortranproject/       > /dev/null 2> /dev/null
cp ./images/fortranproject/16x16/*.* ../../../$CB_OUTPUT_RESDIR/images/fortranproject/16x16/ > /dev/null 2> /dev/null
cp ./images/fortranproject/20x20/*.* ../../../$CB_OUTPUT_RESDIR/images/fortranproject/20x20/ > /dev/null 2> /dev/null
cp ./images/fortranproject/24x24/*.* ../../../$CB_OUTPUT_RESDIR/images/fortranproject/24x24/ > /dev/null 2> /dev/null
cp ./images/fortranproject/28x28/*.* ../../../$CB_OUTPUT_RESDIR/images/fortranproject/28x28/ > /dev/null 2> /dev/null
cp ./images/fortranproject/32x32/*.* ../../../$CB_OUTPUT_RESDIR/images/fortranproject/32x32/ > /dev/null 2> /dev/null
cp ./images/fortranproject/40x40/*.* ../../../$CB_OUTPUT_RESDIR/images/fortranproject/40x40/ > /dev/null 2> /dev/null
cp ./images/fortranproject/48x48/*.* ../../../$CB_OUTPUT_RESDIR/images/fortranproject/48x48/ > /dev/null 2> /dev/null
cp ./images/fortranproject/56x56/*.* ../../../$CB_OUTPUT_RESDIR/images/fortranproject/56x56/ > /dev/null 2> /dev/null
cp ./images/fortranproject/64x64/*.* ../../../$CB_OUTPUT_RESDIR/images/fortranproject/64x64/ > /dev/null 2> /dev/null
cp ./images/fortranproject/svg/*.*   ../../../$CB_OUTPUT_RESDIR/images/fortranproject/svg/   > /dev/null 2> /dev/null
exit 0
