[Toolchains]
; Specify the WinLibs standalone build of GCC and MinGW-w64 for Windows 
; Use GCC 14.2.0 (with POSIX threads) + LLVM/Clang/LLD/LLDB 19.1.7 + MinGW-w64 12.0.0 UCRT
TOOLCHAIN32_HOME=C:\mingw64
TOOLCHAIN64_HOME=C:\mingw64

[Tools]
; Specify the UPX 64-bit path for both UPX variables
UPX32=C:\Program Files\UPX\upx.exe
UPX64=C:\Program Files\UPX\upx.exe

; You don't need to modify anything below this line

[General]
BUILD32=1
BUILD64=1

[Arguments]
FLAGS=-fno-keep-inline-dllexport -Wno-unused-local-typedefs -Wno-deprecated-declarations
VENDOR32=custom
VENDOR64=custom
WINDRES32_FLAGS=--use-temp-file
WINDRES64_FLAGS=
