[Toolchains]
; Specify the WinLibs standalone build of GCC and MinGW-w64 for Windows 
; Use GCC 14.2.0 (with POSIX threads) + LLVM/Clang/LLD/LLDB 19.1.7 + MinGW-w64 12.0.0 UCRT
; This package exists in both 32-bit (x86) and 64-bit (x64)
TOOLCHAIN32_HOME=C:\mingw32
TOOLCHAIN64_HOME=C:\mingw64

[Tools]
; Specify 7-Zip path
SEVENZIP=C:\Program Files\7-Zip\7z.exe

[Settings]
; Specify here the DREAMSDK_HOME_DEBUG_DRIVE you are using in this repository.
; By default, this is the C: drive, i.e., "C:\DreamSDK".
; DREAMSDK_HOME_DEBUG_DRIVE should match the drive specified in:
; .\codeblocks\src\plugins\compilergcc\resources\compilers\compiler_dc-gcc.xml
; .\codeblocks\src\plugins\compilergcc\resources\compilers\options_dc-gcc.xml
DREAMSDK_HOME_DEBUG_DRIVE=C:

; You don't need to modify anything below this line

; Indicate the Code::Blocks version currently built
CB_VERSION=25.03

[General]
BUILD32=1
BUILD64=1

[Arguments]
CB_SOURCE32_DIR_NAME=output32
CB_SOURCE64_DIR_NAME=output32_64
OUTPUT_DIR=dist
